import os

CAMERA_FPS = 15
CAMERA_WIDTH = 640
CAMERA_HEIGHT = 480
ENGAGEMENT_YAW_THRESHOLD_DEG = 20.0
ENGAGEMENT_PITCH_THRESHOLD_DEG = 15.0
ENGAGEMENT_ON_HOLD_SEC = 0.5
ENGAGEMENT_OFF_HOLD_SEC = 1.5
IDLE_AFTER_NO_FACE_SEC = 3.0
SEEK_DELAY_SEC = [5.0, 10.0, 15.0]
OBJECT_DETECT_HZ = 1.0
OBJECT_CONF_THRESHOLD = 0.20
OBJECT_IOU_DUP_THRESHOLD = 0.4
YOLO_MODEL = os.getenv("YOLO_MODEL", "yolov8s.pt")
YOLO_IMAGE_SIZE = int(os.getenv("YOLO_IMAGE_SIZE", "640"))
LAMP_TICK_HZ = 20
WHISPER_MODEL = "tiny.en"
OPENAI_MODEL = "gpt-4o-mini"
TTS_VOICE = "en-US-AriaNeural"
ENABLE_EDGE_TTS = False
DB_PATH = "memory.db"
HISTORY_MAX_MESSAGES = 20
